# Generated by Django 5.0.3 on 2024-06-10 21:16

import django.db.models.deletion
import products_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('price', products_app.models.PositiveDecimalField(decimal_places=2, max_digits=10, validators=[products_app.models.check_positive])),
                ('category_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='products_app.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.category')),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products_app.product')),
            ],
            options={
                'verbose_name': 'relationship product supplier',
                'verbose_name_plural': 'relationships product supplier',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(through='products_app.ProductCategory', to='products_app.product'),
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.product')),
            ],
            options={
                'verbose_name': 'relationship product supplier',
                'verbose_name_plural': 'relationships product supplier',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('rating', models.PositiveIntegerField(validators=[products_app.models.check_rating])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.product')),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=100, validators=[products_app.models.check_phone])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(through='products_app.ProductSupplier', to='products_app.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='productsupplier',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(through='products_app.ProductSupplier', to='products_app.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='productsupplier',
            unique_together={('product_id', 'supplier_id')},
        ),
    ]
