# Generated by Django 5.0.3 on 2024-04-30 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "categories"},
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.CreateModel(
            name="CategoryProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products_app.category",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products_app.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "relateionship product ",
                "unique_together": {("category_id", "product_id")},
            },
        ),
        migrations.AddField(
            model_name="category",
            name="product_id",
            field=models.ManyToManyField(
                through="products_app.CategoryProduct", to="products_app.product"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category_id",
            field=models.ManyToManyField(
                through="products_app.CategoryProduct", to="products_app.category"
            ),
        ),
    ]
