# Generated by Django 5.0.3 on 2024-06-10 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products_app.category'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='products_app.product'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products_app.product'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products_app.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ManyToManyField(to='products_app.category'),
        ),
    ]
