# Generated by Django 5.0.3 on 2024-04-30 10:59

import products_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products_app",
            "0002_alter_category_options_remove_product_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[products_app.models.check_positive],
            ),
        ),
    ]
