# Generated by Django 5.0.3 on 2024-04-30 11:30

import products_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0003_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=products_app.models.PositiveDecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[products_app.models.check_positive],
            ),
        ),
    ]
