# Generated by Django 5.0.3 on 2024-05-13 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0004_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="product_id",
        ),
        migrations.AddField(
            model_name="product",
            name="suppliers",
            field=models.ManyToManyField(
                through="products_app.ProductSupplier", to="products_app.supplier"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="products",
            field=models.ManyToManyField(
                through="products_app.ProductSupplier", to="products_app.product"
            ),
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products_app.category",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products_app.product",
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "relationship product supplier",
                "verbose_name_plural": "relationships product supplier",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="products",
            field=models.ManyToManyField(
                through="products_app.ProductCategory", to="products_app.product"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category_id",
            field=models.ManyToManyField(
                through="products_app.ProductCategory", to="products_app.category"
            ),
        ),
        migrations.DeleteModel(
            name="CategoryProduct",
        ),
    ]
