name: Check
on: [push]
jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 wemake-python-styleguide
    - name: Flake8
      run: flake8 products/ products_app/
  tests:
    name: Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: changed
          POSTGRES_USER: prod
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 38746
          POSTGRES_NAME: postgres
      with:
        python-version: 3.10.6
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Tests
      run: |
        ./manage.py migrate
        ./manage.py test
